/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsIndexRouteImport } from './routes/posts.index'
import { Route as AccommodationsIndexRouteImport } from './routes/accommodations.index'
import { Route as PostsSlugRouteImport } from './routes/posts.$slug'
import { Route as AdminNewRouteImport } from './routes/admin.new'
import { Route as AccommodationsCodeRouteImport } from './routes/accommodations.$code'
import { Route as AdminEditSlugRouteImport } from './routes/admin.edit.$slug'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccommodationsIndexRoute = AccommodationsIndexRouteImport.update({
  id: '/accommodations/',
  path: '/accommodations/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewRoute = AdminNewRouteImport.update({
  id: '/admin/new',
  path: '/admin/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AccommodationsCodeRoute = AccommodationsCodeRouteImport.update({
  id: '/accommodations/$code',
  path: '/accommodations/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEditSlugRoute = AdminEditSlugRouteImport.update({
  id: '/admin/edit/$slug',
  path: '/admin/edit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/accommodations/$code': typeof AccommodationsCodeRoute
  '/admin/new': typeof AdminNewRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/accommodations': typeof AccommodationsIndexRoute
  '/posts': typeof PostsIndexRoute
  '/admin/edit/$slug': typeof AdminEditSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/accommodations/$code': typeof AccommodationsCodeRoute
  '/admin/new': typeof AdminNewRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/accommodations': typeof AccommodationsIndexRoute
  '/posts': typeof PostsIndexRoute
  '/admin/edit/$slug': typeof AdminEditSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/accommodations/$code': typeof AccommodationsCodeRoute
  '/admin/new': typeof AdminNewRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/accommodations/': typeof AccommodationsIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/admin/edit/$slug': typeof AdminEditSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/accommodations/$code'
    | '/admin/new'
    | '/posts/$slug'
    | '/accommodations'
    | '/posts'
    | '/admin/edit/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/accommodations/$code'
    | '/admin/new'
    | '/posts/$slug'
    | '/accommodations'
    | '/posts'
    | '/admin/edit/$slug'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/accommodations/$code'
    | '/admin/new'
    | '/posts/$slug'
    | '/accommodations/'
    | '/posts/'
    | '/admin/edit/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AccommodationsCodeRoute: typeof AccommodationsCodeRoute
  AdminNewRoute: typeof AdminNewRoute
  PostsSlugRoute: typeof PostsSlugRoute
  AccommodationsIndexRoute: typeof AccommodationsIndexRoute
  PostsIndexRoute: typeof PostsIndexRoute
  AdminEditSlugRoute: typeof AdminEditSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accommodations/': {
      id: '/accommodations/'
      path: '/accommodations'
      fullPath: '/accommodations'
      preLoaderRoute: typeof AccommodationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$slug': {
      id: '/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/new': {
      id: '/admin/new'
      path: '/admin/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AdminNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accommodations/$code': {
      id: '/accommodations/$code'
      path: '/accommodations/$code'
      fullPath: '/accommodations/$code'
      preLoaderRoute: typeof AccommodationsCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/edit/$slug': {
      id: '/admin/edit/$slug'
      path: '/admin/edit/$slug'
      fullPath: '/admin/edit/$slug'
      preLoaderRoute: typeof AdminEditSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AccommodationsCodeRoute: AccommodationsCodeRoute,
  AdminNewRoute: AdminNewRoute,
  PostsSlugRoute: PostsSlugRoute,
  AccommodationsIndexRoute: AccommodationsIndexRoute,
  PostsIndexRoute: PostsIndexRoute,
  AdminEditSlugRoute: AdminEditSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
